### PR TITLE
Add support for custom update sources in the C++ library

### PR DESCRIPTION
**Pull request by plumenator**
This is an initial attempt. I managed to make this work with a private AWS S3 bucket as the update source. Please let me know if I need to update any tests or sample code

### CODE REVIEW

**Comment by caesay** [comment]
Hey, thanks for this PR. I've rebased to latest, and pushed a new commit with some changes to the rust c header. Firstly, do you think the approach is on the right track? Secondly, if you agree with the direction would you mind updating the Velopack.hpp c++ header to align with the new C functions?

**Comment by plumenator** [comment]
@caesay Sorry, I just saw this. I guess you made reasonable choices? Please let me know if you'd like me to do anything more. Glad that the change is in main!

**Comment by caesay** [comment]
The changes have been released, and there is an example in the `CPlusPlusWidgets` sample. Could you please review/test that the final implementation is suitable?

**Comment by plumenator** [comment]
I integrated with our app and tested it. It works as intended.

**Pull request merged**
