### PR TITLE
add s3 prefix support

### LINKED ISSUE #148: Error uploading to HTTP S3 endpoints
If trying to upload to an HTTP endpoint, you get the following error:

> When DisablePayloadSigning is true, the request must be sent over HTTPS., retrying in 1 second. 

Presumably we actually _do_ want payload signing to be on by default. So we're going to need to make disabling it optional with a CLI arg.

### PR DESCRIPTION
**Pull request by fran6co**
Fixes https://github.com/velopack/velopack/issues/168
Fixes #148

### CODE REVIEW

**Comment by caesay** [comment]
Thanks for the contribution! The way this is currently written, I think updating will break if the prefix does not end in a `/` character. 

Thexe would not be a valid URL and would produce errors in `SimpleWebSource`:
- "https://s3-bucket.somedomain.com/somprefixreleases.win.json" or;
- "https://s3-bucket.somedomain.com/somprefixYourApp-1.0.0-full-nupkg"

But these would be valid:
- "https://s3-bucket.somedomain.com/somprefix/releases.win.json" or;
- "https://s3-bucket.somedomain.com/somprefix/YourApp-1.0.0-full-nupkg"

So either we can add a command line validation to reject prefix's which do not end with `/` or we'd need to add it if it's missing in the S3 uploader

**Comment by fran6co** [comment]
I was thinking about leaving it to the user discretion, but I added the / if it's not there now

**Review by caesay — CHANGES_REQUESTED** [review]
Since the following lines of code use the AmazonS3Client directly, I don't think the prefix will be used correctly. Perhaps we should make the AmazonS3Client a private member of the S3BucketClient class. 
https://github.com/velopack/velopack/pull/169/files#diff-6bf2bce0876e8ec6d74ab30e7b1da831e723fa185b774c5774aab29db3665a60R180-R187

**Comment by fran6co** [comment]
Is this ok? I haven't been doing much C#

**Review by caesay — DISMISSED** [review]
Looks good! Thanks, I'll try and get it merged later today.

**Comment by caesay** [comment]
> Thanks! Great project btw, just started integrating to our stack and it's a lot easier to use than all the other alternatives

Would love to hear more about this, if you're willing? eg. what you've tried before Velopack, what was easier about Velopack, what's your fav feature or what would you like to see added?

**Comment by fran6co** [comment]
We haven't tried others, did a survey of the options and found that Squirrel looked like the best option. But then found out it was not getting maintained anymore and looked for alternatives similar to it and found velopack. I really like being able to easily pack apps and self updating. I think features wise I would like to be able explicitly set the files to be packed as a list instead of having to give a directory and then exclude. Also being able to customize the shortcuts (passing parameters to the exe) in the installer from C++ code, I saw some examples for C# only.

**Comment by caesay** [comment]
I think https://github.com/velopack/velopack/issues/46 may solve your concern about shortcuts on C++

**Pull request merged**
